# Generated by Django 4.2.4 on 2023-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('aadhar', models.BigIntegerField()),
                ('contact', models.BigIntegerField()),
                ('adress', models.CharField(max_length=150)),
                ('userimg', models.ImageField(upload_to='user/')),
            ],
        ),
    ]
