# Generated by Django 4.2.4 on 2023-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_verifystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verifyotp',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
