# Generated by Django 4.2.4 on 2023-10-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_verifyotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productdetail', models.CharField(max_length=150)),
                ('productprice', models.IntegerField()),
                ('returndue', models.DateField()),
                ('productimg', models.ImageField(blank=True, upload_to='product/')),
                ('fleatchdate', models.DateField(auto_now_add=True)),
                ('intrest', models.DecimalField(decimal_places=2, max_digits=8)),
                ('released', models.BooleanField(default=False, help_text='0-default,1-true')),
                ('releasedate', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
