# Generated by Django 4.2.4 on 2023-10-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_intrest_alter_product_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='intrest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='released',
            field=models.BooleanField(blank=True, default=False, help_text='0-default,1-true', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='releasedate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
