# Generated by Django 4.2.4 on 2023-10-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_intrest_alter_product_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='releasedate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
