# Generated by Django 4.2.4 on 2023-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transfer',
            field=models.BooleanField(blank=True, default=False, help_text='0-default,1-true', null=True),
        ),
    ]
